using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace CMS
{
    public partial class AddNewConference : Form
    {
        private Conference conference;
        public AddNewConference()
        {
            InitializeComponent();
            conference = new Conference();
        }

        private void button2_Click(object sender, EventArgs e)
        {
            ManageConferenceUI manageConference = new ManageConferenceUI();
            manageConference.Show();
            this.Hide();
        }

        private void createConference_Click(object sender, EventArgs e)
        {
            string name = conferenceName.Text.Trim();
            string venue = conferenceVenue.Text.Trim();
            string description = conferenceDescription.Text.Trim();
            DateTime date = conferenceDate.Value;
            int capacity = (int)conferenceCapacity.Value;

            // Validate the input
            if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(venue) || string.IsNullOrEmpty(description))
            {
                MessageBox.Show("Please fill in all the required fields.");
                return;
            }

            if (capacity <= 0)
            {
                MessageBox.Show("Please enter a valid conference capacity.");
                return;
            }

            // Call the method to create the new conference (the ID will be auto-generated by the database)
            conference.CreateConference(name, date, venue, description, capacity);

            // Optionally, you can close the form after saving
            this.Close();
        }
    }
}
